'''
PROJETO Nº 6 - DESAFIO DE MATEMÁTICA.

NESSE CÓDIGO, VAMOS ELABORAR UM DESAFIO NO QUAL SERÃO EXIBIDOS PROBLEMAS MATEMÁTICOS, NO QUAL O USUÁRIO DEVERÁ
SOLUCIONAR, NÃO SERÁ EXIBIDO UM NOVO PROBLEMA MATEMÁTICO ATÉ O USUÁRIO SOLUCIONAR O PROBLEMA EXIBIDO. 
'''

import random

OPERADORES = ['+', '-', '/', '*']
MIN_OPERAND = 3
MAX_OPERAND = 12